server:
  port: 8020
spring:
  application:
    name: consumer
  eureka:
    client:
      servicce-url:
        defaultZone: http://localhost:8761/eureka/
    instance:
      prefer-ip-address: true
