server:
  port: 8050
spring:
  application:
    name: feign
eureka:
    client:
      servie-url:
        defaultZone: http://localhost:8761/eureka/
      instance:
        prefer-id-address: true
feign:
  hystrix:
    enabled: true
